### ISSUE TITLE
Translation: The POI details page should be translated in UI

### ISSUE THREAD

**Issue by solarpete** [openchargemap/ocm-system#74] opened 2015-10-17 13:56 UTC
The following parts of the page still need to be made translateable:

![15poi_details_01](https://cloud.githubusercontent.com/assets/9208139/10559061/759bf13c-74e7-11e5-91d2-421628096598.PNG)

![15poi_details_02](https://cloud.githubusercontent.com/assets/9208139/10559064/9430cc6c-74e7-11e5-96de-14f8e927d7f1.PNG)

![15poi_details_03](https://cloud.githubusercontent.com/assets/9208139/10559066/95edc2c6-74e7-11e5-9853-870263cc3662.PNG)

![15poi_details_04](https://cloud.githubusercontent.com/assets/9208139/10559067/98526e72-74e7-11e5-97e6-8f79c9d31b47.PNG)

![15poi_details_05](https://cloud.githubusercontent.com/assets/9208139/10559073/9b01baf6-74e7-11e5-8bf4-226b11e37e90.PNG)

**Comment by solarpete** [comment] 2015-10-17 18:44
Also the following buttons should be made translatable (they appear when the user is not signed in):

![image](https://cloud.githubusercontent.com/assets/9208139/10560594/d3939286-750f-11e5-965d-a1c06eb37ad2.png)

**Comment by solarpete** [comment] 2015-10-17 18:45
And one for Uploading photos as well:

![image](https://cloud.githubusercontent.com/assets/9208139/10560603/097f84f4-7510-11e5-93df-f119ce678134.png)

**Comment by solarpete** [comment] 2015-10-17 20:48
Chris,
I submitted a pull request with some work done for this issue. 
However it is still not finished, as (apart from what I don't know how to do and we discussed so far) I could not simulate signing myself in when trying it out on localhost. I tried using my credentials and always got the "GeneralError" page (\ocm-system\Website\OCM.MVC\Views\Home\GeneralError.cshtml). 
Is there some trick how to get past this or how do you try your changes out? Or could it be caused by incomplete environment for simulation of the website?

**Comment by webprofusion-chrisc** [comment] 2015-10-18 02:55
Hi Pete, 
You should be able to register as a new user even if your own credentials aren't available. Sounds like something is going wrong but I'd need to know the exception (usually shown in the Output window in visual studio). I suspect the database may have an out of date schema but can't tell. 

I'll update the OCM_Export database backup so you can use that.

To login as any user for testing you can add the following at the start of the "Index" method of Controllers/HomeController.cs:

if (Session["UserID"] == null)
            {
                OCM.MVC.Controllers.LoginProviderController.PerformCoreLogin(new OCM.API.Common.UserManager().GetUser(1000));
                return RedirectToAction("Index");
            }

**Comment by webprofusion-chrisc** [comment] 2015-10-18 03:11
I'm uploading an updated OCM_Clone_Backup.zip to GitHub now (under ocm-docs/database/) this has recent data and the latest schema.

**Comment by webprofusion-chrisc** [comment] 2015-10-18 10:36
I had a backlog of stuff to commit today, one of which was a previous change to the POI Details page which I merged with your most recent pull request. My changed added translation of reference data types such as Usage type etc and equipment info such as Connection type

**Comment by solarpete** [comment] 2015-10-18 11:11
OK, I will check your changes and then try to do as much as possible for this issue with the new knowledge I have from your replys. Are you planning to commit anything else today? (I would like to start a new branch when you are finished so that the changes will be easier to merge.)

**Comment by webprofusion-chrisc** [comment] 2015-10-18 12:19
No nothing else today and probably not much until Friday/next weekend. I have mainly been working on API stuff and part of the app javascript.

**Comment by solarpete** [comment] 2015-10-18 13:24
Chris, I wanted to continue today, but I keep getting the following exception:

![exception_20151018_02](https://cloud.githubusercontent.com/assets/9208139/10564206/4d58f0ca-75ab-11e5-8cd4-cae1fb4e5a0a.png)

Unfortunately updating the database from the fresh clone did not help, neither did getting back to the branch I was using yesterday (without the changes you checked-in today). The second one quite worries me, because I think it should work, but the only advantage over the latest code is that I do not get the NuGet Package restore error.

Any idea what could be the cause? Thank you!

**Comment by webprofusion-chrisc** [comment] 2015-10-18 23:25
That looks like a visual studio/iisexpress glitch as Session shouldnt really be null (make sure the asp.net session state service is running and set to auto start). Just try restarting your machine.

**Comment by webprofusion-chrisc** [comment] 2015-10-18 23:27
You coild also update VS to VS2015 community edition and remove vs2013 if you wanted, but that can take a few hours.

**Comment by solarpete** [comment] 2015-10-21 20:20
Thanks Chris. I will update the Visual Studio. Actually I need to start using different machine anyway, so I will need to reinstall all the tools on the other PC, so if you switched to a different version of any other tool please let me know. And it seems that I will be quite busy over the coming weeks, so it will probably take some time till I am done and can continue the work on translations...

**Comment by solarpete** [comment] 2015-10-25 08:11
Hi Chris, I have successfully installed the development tools on my other machine and the exceptions disappeared :-)
However the translation do not work for me with the latest code, i.e. changing the language code to any language does not apply translations:
![broken_translations_01](https://cloud.githubusercontent.com/assets/9208139/10714629/fadc4b56-7af7-11e5-81e3-335a8048c907.png)

I tried it with the code with your commits both from 25th and 23rd of October with the same result. However when I revert to code when you merged my latest commit (on 17th of October), it seems to work OK.
Could you confirm that the translations work for you with the latest changes?

**Comment by webprofusion-chrisc** [comment] 2015-10-25 10:40
Hi Pete, can you check under [Chrome Menu] > More Tools > Developer Tools that there are no javascript errors being reported on the browser console? I can confirm that the build I have is currently showing translations but there may well be some sort of difference. 

When you run your build do the javascript files under Website\OCM.MVC\Scripts\OCM\SharedLibs update? These are built by the app then should be copied over to the website so that we can re-use certain javascript code.

**Closed** 2018-01-17 02:08 UTC
Labels: OCM Website, enhancement, translation
